# Generated by Django 4.2.3 on 2023-07-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mercadoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True)),
                ('tipo', models.CharField(choices=[('Móvel', 'Móvel'), ('Eletrônico', 'Eletrônico'), ('Eletrônico', 'Eletrônico'), ('Vestuário', 'Vestuário'), ('Beleza', 'Beleza')], max_length=100, null=True)),
                ('fabricante', models.CharField(max_length=100, null=True)),
                ('descricao', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
