# Generated by Django 4.2.3 on 2023-07-23 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_mercadoria_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveBigIntegerField(null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('mercadoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.mercadoria')),
            ],
        ),
    ]
