# Generated by Django 4.2.3 on 2023-07-23 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
