# Generated by Django 4.2.3 on 2023-07-24 02:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_entrada_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrada',
            options={'verbose_name_plural': 'Entrada'},
        ),
        migrations.AlterModelOptions(
            name='mercadoria',
            options={'verbose_name_plural': 'Mercadoria'},
        ),
        migrations.AlterField(
            model_name='entrada',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 2, 8, 57, 291853, tzinfo=datetime.timezone.utc)),
        ),
    ]
