# Generated by Django 4.2.3 on 2023-07-24 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_entrada_options_alter_mercadoria_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
