# Generated by Django 4.2.3 on 2023-08-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_entrada_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercadoria',
            name='quantidade',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
