# Generated by Django 4.2.3 on 2023-08-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_mercadoria_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercadoria',
            name='quantidade',
            field=models.IntegerField(null=True),
        ),
    ]
