# Generated by Django 4.2.3 on 2023-08-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_mercadoria_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercadoria',
            name='entradaQuantidade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mercadoria',
            name='saidaQuantidade',
            field=models.IntegerField(default=0),
        ),
    ]
